### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dhardiman** [jnfisher/ios-curve-interpolation#1]
Hi John,

I've just discovered this repository and it's exactly what I'm looking for. Is there a specific license covering the work here?

Thanks

Dave

**Comment by jnfisher** [comment]
Hi Dave,
I'm glad you found the project useful.  My intent is for anyone to use it, free of charge, in any way they like.  To this end, I've added the permissive MIT License to the project.  Enjoy!

John

**Comment by dhardiman** [comment]
That's brilliant, thanks!
