### ISSUE TITLE
Bézier Path point

### ISSUE THREAD

**Issue by ronakcc** [jnfisher/ios-curve-interpolation#2]
Hello,
Thanks for this code. It really helpful for me.
This code is perfect but my suggestion is that if u  can move Bézier Path point  so it's more perfect than before....

**Comment by jnfisher** [comment]
Hi ronakcc,
I don't follow- can you describe what you'd like in more detail?

**Comment by ronakcc** [comment]
Hello,
Thanks for reply!

I mean to say when we set a bezier path point so after we set bezier path point so this point should be movable..
See this image so you will get more idea about this.
![screen shot 2015-02-17 at 11 16 37 am](https://cloud.githubusercontent.com/assets/4251737/6223756/84ae923e-b696-11e4-9626-941035808630.png)

**Comment by ronakcc** [comment]
![screen shot 2015-02-17 at 11 16 37 am](https://cloud.githubusercontent.com/assets/4251737/6223859/271edf82-b698-11e4-8acd-87090d560997.png)

**Comment by jnfisher** [comment]
Thanks for the suggestion!  

Yes, that's something I'd like to add.  My plan for this project is to port it to Swift and create a cocoapod so its easier to use/install.  At that time, I will consider making the points draggable.

**Comment by ronakcc** [comment]
Hello John,
I need your help...can you develop draggable point code for me becz i tried a lot bt it was not work properly..so if you have a time so send me early as possible..nd thanx for your positive reply dear..
